
# In this script we begin to experiment with spline modeling of tones generated by two pitches.
# For example, two notes played and recorded as one waveform, say a perfect fifth apart.
# We can still think of the tone as an approximately periodic waveform made up of cycles.
# The ratio of 3/2 between the fundamental frequencies, say f1 and f2 = (3/2)*f1, means that
# we have a basically periodic waveform with cycle length 3*s1 = 2*s2, where s1 and s2 are
# the cycle lengths associated to f1 and f2.  When we listen to such a waveform we of course
# hear the two individual frequencies, but we should also perceive a lower frequency coming
# from the new cycle length, given by (1/2)*f1 = (1/3)*f2.  

# We could try to accentuate this undertone by shaping an envelope over each cycle ...

# Doing cycle interpolation on these longer "polyphonic cycles" could be interesting,
# for example we could replace 3/2 above by 5/4 (major third) and 5/3 (major sixth). 
# The "polyphonic cycle" would have length 5 times the shorter cycle length, mixed with
# the other (lower) tone's cycle length, either 4 or 3 of those.  So we could produce
# two different polyphonic waveforms, each with the same length polyphonic cycles.  Then
# we could morph between these using cycle interpolation.  Since each of these will have
# the same upper note, one would expect to hear the lower pitch changing from a ...
