
# In this script we begin to experiment with spline modeling of tones generated by two pitches.
# For example, two notes played and recorded as one waveform, say a (Just) perfect fifth apart.
# We can still think of the tone as an approximately periodic waveform made up of cycles.
# The ratio of 3/2 between the fundamental frequencies, say f1 and f2 = (3/2)*f1, means that
# we have a basically periodic waveform with cycle length 3*s1 = 2*s2, where s1 and s2 are
# the cycle lengths associated to f1 and f2.  When we listen to such a waveform we of course
# hear the two individual frequencies, but we should also perceive a lower frequency coming
# from the new cycle length, given by (1/2)*f1 = (1/3)*f2.  

# We could try to accentuate this undertone by shaping an envelope over each cycle ...

# A simple experiment in tone generation could be to start with one polyphonic cycle
# say with f1=200 and f2=300 and cycle of length s = 2*s1 = 3*s2 = 1/100 sec.  Then
# do a cycle interpolation over 1 or 2 seconds to reach a non-polyphonic cycle of
# the same length.  

# Doing cycle interpolation on these longer "polyphonic cycles" could be interesting,
# for example we could replace 3/2 above by 5/4 (major third) and 5/3 (major sixth). 
# The "polyphonic cycle" would have length 5 times the shorter cycle length, mixed with
# the other (lower) tone's cycle length, either 4 or 3 of those.  So we could produce
# two different polyphonic waveforms, each with the same length polyphonic cycles.  Then
# we could morph between these using cycle interpolation.  Since each of these will have
# the same upper note, one would expect to hear the lower pitch changing from a major
# third lower to a major sixth lower.  This could be an effect to produce a sound which
# evolves over say one second with an undertone shifting in pitch.  

# The amount of perceptive pitch at the level of the cycle being interpolated could be
# influenced by some shaping of chosen cycles, say like a raised cosine window or other
# shape, in order to emphasize the definition of each cycle of chosen size.  Since there
# are several pitches in the above example, say 300 Hz and two undertones:
# (4/5)*300 = 240 Hz, and (3/5)*300 = 180 Hz, one could focus on any one of these in order
# to emphasize that frequency by shaping cycles of the appropriate length.  

# To shape cycles one could use a simple polynomial curve instead of raised cosine. For
# example, on the interval [0,1] we could use a parabola through three points: 
# (0, 0.8), (0.5, 1), (1, 0.8).

# In order to model a repeated shape, several times, to form a B-spline model of one longer
# polyphonic cycle, one could use particular knot sequence, with repeats in the middle.
# It might be easier, however, to simply generate several cycles of different lengths, say
# related by some fraction as above, and mix these to one waveform as polyphonic cycle.
# This polyphonic cycle would then be represented only at the sample level.  But then we
# could use the new idea of simply taking a subset of the samples and using them as B-spline 
# coefficients. This gives a crude way to represent a polyphonic cycle.  Then we could do a 
# cycle interpolation, perhaps morphing to a monophonic cycle.

# Steps:
# 1. select n B-spline coefficients for a cycle.
# 2. generate 2 cycles at 200 Hz with cycle length 1/200 sec, 
# 3. generate 3 cycles at 300 Hz with cycle length 1/300 sec, 
# 4. mix these to get polyphonic cycle at 100 Hz, of length 1/100 sec.
# 5. use a subset of the samples of this poly-cycle as new bcoeffs.
# 6. morph from the poly-cycle to a mono-cycle at 100 Hz.




